name: Cypress API Tests
on: 
    pull_request:
        branches: [main]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6

